package pt.isel

/**
 * Generic repository interface for basic CRUD operations,
 * except for insert, which is omitted because the primary key (PK)
 * may be generated by the database and varies between entities.
 */
interface Repository<K, T> {
    fun getById(id: K): T? // Find an entity by its ID

    fun getAll(): List<T> // Retrieve all entities

    fun update(entity: T) // Update an existing entity

    fun deleteById(id: K) // Delete an entity by its ID
}
